apps/accounts/urls.py
from django.urls import path
from . import views

app_name= 'accounts'
urlpatterns = [
    path('register/',views.UserRegisterView.as_view(), name='register'),
    path('verify/',views.VerifyRegisterCodeView.as_view(), name='verify'),
    path('login/',views.LoginUserView.as_view(), name='login'),
    path('logout/',views.LogoutUserView.as_view(), name='logout'),
    
    path('userpanel/',views.UserPanelView.as_view(), name='userpanel'), 
    path('show_last_orders',views.show_last_orders, name='show_last_orders'), 
    path('show_user_payments',views.show_user_payments, name='show_user_payments'), 
    path('change_password/',views.ChangePasswordView.as_view(), name='change_password'), 
    path('remember_password/',views.RememberPasswordView.as_view(), name='remember_password'), 
]

onlineshop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('apps.main.urls',namespace='main')),
    path('accounts/',include('apps.accounts.urls',namespace='accounts')),
    path('products/',include('apps.products.urls',namespace='products')),
    path('orders/',include('apps.orders.urls',namespace='orders')),
    path('discounts/',include('apps.discounts.urls',namespace='discounts')),
    path('payments/',include('apps.payments.urls',namespace='payments')),
    path('feedback/',include('apps.feedback.urls',namespace='feedback')),
    path('search/',include('apps.search.urls',namespace='search')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

handler404 = 'apps.main.views.handler404'

templates/accounts_app/changepassword.html
{% extends 'main_template.html' %}

{% block title %}
Home Page
{% endblock title %}



{% block content %}
		<!-- site__body -->
		<div class="site__body">
			<div class="page-header">
				<div class="page-header__container container">
					<div class="page-header__breadcrumb">
						<nav aria-label="breadcrumb">
							<ol class="breadcrumb">
								<li class="breadcrumb-item"><a href="index.html">Home</a>
									/
								</li>
								<li class="breadcrumb-item">
									<a href="">حساب کاربری</a>
									/
								</li>
								<li class="active" aria-current="page">Change User Account Password</li>
							</ol>
						</nav>
					</div>
					<div class="page-header__title d-flex justify-content-center">
						<h1>Change User Account Password</h1></div>
				</div>
			</div>
			<div class="block">
				<div class="container">
					<div class="row d-flex justify-content-center">
						<div class="col-md-6 d-flex mt-4 mt-md-0">
							<div class="card flex-grow-1 mb-0">
								<div class="card-body">
									<h3 class="card-title">Change Password</h3>

                                    <form method="post">
                                        {% csrf_token %}
                                        {{form.as_p}}
										<button type="submit" class="btn btn-primary mt-4">ثبت نام</button>
									</form>
                                    
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- site__body / end -->

{% endblock content %}

templates/accounts_app/login.html
{% extends 'main_template.html' %}

{% block title %}
Home Page
{% endblock title %}



{% block content %}
		<!-- site__body -->
		<div class="site__body">
			<div class="page-header">
				<div class="page-header__container container">
					<div class="page-header__breadcrumb">
						<nav aria-label="breadcrumb">
							<ol class="breadcrumb">
								<li class="breadcrumb-item"><a href="index.html">خانه</a>
									/
								</li>
								<li class="breadcrumb-item">
									<a href="#">حساب کاربری</a>
									/
								</li>
								<li class="active" aria-current="page">ورود به حساب کاربری</li>
							</ol>
						</nav>
					</div>
					<div class="page-header__title d-flex justify-content-center">
						<h1>ورود به حساب کاربری</h1>
					</div>
				</div>
			</div>
			<div class="block">
				<div class="container">
					<div class="row d-flex justify-content-center">
						<div class="col-md-6">
							<div class="card flex-grow-1 mb-md-0">
								<div class="card-body">
									<h3 class="card-title">ورود</h3>

                                    <form method="post">
                                        {% csrf_token %}
                                        {{form.as_p}}
                                        <div>
                                            <a href="{% url 'accounts:remember_password' %}">Forgot password</a>
                                        </div>
										<button type="submit" class="btn btn-primary mt-4">ورود</button>
									</form>

								</div>
							</div>
						</div>

					</div>
				</div>
			</div>
		</div>
		<!-- site__body / end -->
{% endblock content %}

templates/accounts_app/register.html
{% extends 'main_template.html' %}

{% block title %}
Home Page
{% endblock title %}



{% block content %}
    <h1>register</h1>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Register"/>
    </form>
{% endblock content %}

templates/accounts_app/rememberpassword.html
{% extends 'main_template.html' %}

{% block title %}
Home Page
{% endblock title %}



{% block content %}



		<!-- site__body -->
		<div class="site__body">
			<div class="page-header">
				<div class="page-header__container container">
					<div class="page-header__breadcrumb">
						<nav aria-label="breadcrumb">
							<ol class="breadcrumb">
								<li class="breadcrumb-item"><a href="index.html">خانه</a>
									/
								</li>
								<li class="breadcrumb-item">
									<a href="#">Account</a>
									/
								</li>
								<li class="active" aria-current="page">Authenticate</li>
							</ol>
						</nav>
					</div>
					<div class="page-header__title d-flex justify-content-center">
						<h1>Your phone number to change password</h1>
					</div>
				</div>
			</div>
			<div class="block">
				<div class="container">
					<div class="row d-flex justify-content-center">
						<div class="col-md-6">
							<div class="card flex-grow-1 mb-md-0">
								<div class="card-body">

                                    <form method="post">
                                        {% csrf_token %}
                                        {{form.as_p}}
										<button type="submit" class="btn btn-primary mt-4">ارسال کد</button>
									</form>

								</div>
							</div>
						</div>

					</div>
				</div>
			</div>
		</div>
		<!-- site__body / end -->


{% endblock content %}

templates/accounts_app/show_user_payments.html
{% extends 'user_panel_template.html' %}
{% load humanize %}

{% block title %}
User Payments
{% endblock title %}

{% block content %}
<div class="dashboard__orders card">
    <div class="card-header">
        <h5>Your Payment</h5></div>
    <div class="card-divider"></div>
    <div class="card-table">
        <div class="table-responsive-sm">
            <table>
                <thead>
                    <tr>
                        <th>Number payment</th>
                        <th>Date</th>
                        <th>Status</th>
                        <th>Total</th>
                    </tr>
                </thead>
                <tbody>
                    {% for payment in payments %}
                        <tr>
                            <td><a href="">{{payment.id}}</a></td>
                            <td>{{payment.register_date}}</td>
                            <td>
                                {% if payment.is_finally %}
                                    <span class="text-success">Paid</span>
                                {% else %}
                                    <span class="text-danger">Unpaid</span>
                                {% endif %}
                            </td>
                            <td>{{payment.amount|intcomma}}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock content %}

templates/accounts_app/update_profile.html
{% extends 'user_panel_template.html' %}

{% block title %}
Profile
{% endblock title %}

{% block content %}
    <div class="block">
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="col-md-9">
                    <div class="card flex-grow-1 mb-md-0">
                        <div class="card-body">
                            <h3 class="card-title">Edit your profile</h3>
                            <form action="" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                {{form.as_p}}
                                {% if media_url %}
                                    <img src="{{media_url}}{{media_url}}" alt="" style="width: 100px; height: 100px; border-radius: 5px;">
                                {% else %}
                                    <img src="{{media_url}}/images/customer/nophoto.png" alt="" style="width: 100px; height: 100px; border-radius: 5px;">
                                {% endif %}
                                <div class="form-group">
                                    <button type="submit" class="btn btn-primary mt-4">Edit</button>
                                    <a href="{% url 'accounts:userpanel' %}" class="btn btn-info mt-4">Cansel</a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/accounts_app/userpanel.html
{% extends 'main_template.html' %}
{% load render_partial %}

{% block title %}
Home Page
{% endblock title %}



{% block content %}
    <div class="dashboard">
        {% include 'accounts_app/partials/user_info.html' %}
        {% render_partial 'accounts:show_last_orders' %}
    </div>
{% endblock content %}

templates/accounts_app/verifycode.html
{% extends 'main_template.html' %}

{% block title %}
Home Page
{% endblock title %}



{% block content %}



		<!-- site__body -->
		<div class="site__body">
			<div class="page-header">
				<div class="page-header__container container">
					<div class="page-header__breadcrumb">
						<nav aria-label="breadcrumb">
							<ol class="breadcrumb">
								<li class="breadcrumb-item"><a href="index.html">خانه</a>
									/
								</li>
								<li class="breadcrumb-item">
									<a href="#">حساب کاربری</a>
									/
								</li>
								<li class="active" aria-current="page">احراز هویت</li>
							</ol>
						</nav>
					</div>
					<div class="page-header__title d-flex justify-content-center">
						<h1>تایید شماره موبایل</h1>
					</div>
				</div>
			</div>
			<div class="block">
				<div class="container">
					<div class="row d-flex justify-content-center">
						<div class="col-md-6">
							<div class="card flex-grow-1 mb-md-0">
								<div class="card-body">

                                    <form method="post">
                                        {% csrf_token %}
                                        {{form.as_p}}

										{% comment %} <div class="form-group">
											<label>کد دریافتی</label>
											<input type="text" class="form-control" placeholder="کد دریافتی را وارد کنید">
										</div> {% endcomment %}

										<button type="submit" class="btn btn-primary mt-4">ارسال کد</button>
									</form>
								</div>
							</div>
						</div>

					</div>
				</div>
			</div>
		</div>
		<!-- site__body / end -->


{% endblock content %}