apps/orders/urls.py
from django.urls import path
from . import views

app_name= 'orders'
urlpatterns = [
    path('shop_cart/',views.ShopCartView.as_view(), name='shop_cart'),
    path('show_shop_cart/',views.show_shop_cart, name='show_shop_cart'),
    path('add_to_shop_cart/',views.add_to_shop_cart, name='add_to_shop_cart'),
    path('delete_from_shop_cart/',views.delete_from_shop_cart, name='delete_from_shop_cart'),
    path('update_shop_cart/',views.update_shop_cart, name='update_shop_cart'),
    path('status_of_shop_cart/',views.status_of_shop_cart, name='status_of_shop_cart'),
    path('create_order/',views.CreateOrderView.as_view(), name='create_order'),
    path('checkout_order/<int:order_id>',views.CheckoutOrderView.as_view(), name='checkout_order'),
]

onlineshop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('apps.main.urls',namespace='main')),
    path('accounts/',include('apps.accounts.urls',namespace='accounts')),
    path('products/',include('apps.products.urls',namespace='products')),
    path('orders/',include('apps.orders.urls',namespace='orders')),
    path('discounts/',include('apps.discounts.urls',namespace='discounts')),
    path('payments/',include('apps.payments.urls',namespace='payments')),
    path('feedback/',include('apps.feedback.urls',namespace='feedback')),
    path('search/',include('apps.search.urls',namespace='search')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

handler404 = 'apps.main.views.handler404'

templates/order_app/partials/show_shop_cart.html
{% load humanize %}
{% if shop_cart_count > 0 %}
	<div class="site__body">
		<div class="page-header">
			<div class="page-header__container container">
				<div class="page-header__breadcrumb">
					<nav aria-label="breadcrumb">
						<ol class="breadcrumb">
							<li class="breadcrumb-item"><a href="index.html">Home</a>
								/
							</li>
							<li class="breadcrumb-item active" aria-current="page">Shop cart</li>
						</ol>
					</nav>
				</div>
				<div class="page-header__title">
					<h1>Shop cart</h1></div>
			</div>
		</div>
		<div class="cart block">
			<div class="container">
				<table class="cart__table cart-table">
					<thead class="cart-table__head">
						<tr class="cart-table__row">
							<th class="cart-table__column cart-table__column--image">Image</th>
							<th class="cart-table__column cart-table__column--product">Product</th>
							<th class="cart-table__column cart-table__column--price">Price</th>
							<th class="cart-table__column cart-table__column--quantity">Quantity</th>
							<th class="cart-table__column cart-table__column--total">Total Price</th>
							<th class="cart-table__column cart-table__column--remove"></th>
						</tr>
					</thead>
					<tbody class="cart-table__body">
                        {% for item in shop_cart %}
                            <tr class="cart-table__row">
                                <td class="cart-table__column cart-table__column--image">
                                    <a href=""><img src="images/products/p1.jpg" alt=""></a>
                                </td>
                                <td class="cart-table__column cart-table__column--product">
                                    <a href="" class="cart-table__product-name">
                                        {{item.product.product_name}}
                                    </a>
                                </td>
                                <td class="cart-table__column cart-table__column--price" data-title="قیمت">
									{% if item.final_price < item.price %}
										<del>{{item.price|intcomma}} $</del>
										{{item.final_price|intcomma}} $
									{% else %}
										{{item.price|intcomma}} $
									{% endif %}
									
								</td>
                                <td class="cart-table__column cart-table__column--quantity" data-title="تعداد">
                                    <div class="input-number">
                                        <input id="qty_{{item.product.id}}" type="number" min="1" value="{{item.qty}}" style="width: 60px;">
                                    </div>
                                </td>
                                <td class="cart-table__column cart-table__column--total" data-title="جمع کل">{{item.total_price|intcomma}} $</td>
                                <td class="cart-table__column cart-table__column--remove">
                                    <a type="button" onclick="delete_from_shop_cart({{item.product.id}})" class="btn btn-light btn-sm btn-svg-icon">
                                        <i class="fa fa-trash"></i>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
					</tbody>
				</table>
				<div class="cart__actions">
					<div class="cart__buttons">
						<a href="index.html" class="btn btn-light">Continue shopping</a>
						<a class="btn btn-primary cart__update-button" onclick="update_shop_cart()">Udpade</a></div>
				</div>
				<div class="row justify-content-end pt-5">
					<div class="col-12 col-md-7 col-lg-6 col-xl-5">
						<div class="card">
							<div class="card-body">
								<h3 class="card-title">Total shop cart</h3>
								<table class="cart__totals">
									<thead class="cart__totals-header">
										<tr>
											<th>Price</th>
											<td>{{total_price|intcomma}} $</td>
										</tr>
									</thead>
									<tbody class="cart__totals-body">
										<tr>
											<th>Shipping</th>
											<td>{{delivery|intcomma}} $
												<div class="cart__calc-shipping"><a href="#"></a></div>
											</td>
										</tr>
										<tr>
											<th>Tax</th>
											<td>{{tax|intcomma}} $</td>
										</tr>
									</tbody>
									<tfoot class="cart__totals-footer">
										<tr>
											<th>Total price</th>
											<td>{{order_final_price|intcomma}} $</td>
										</tr>
									</tfoot>
								</table>
								<a class="btn btn-primary btn-xl btn-block cart__checkout-button" href="{% url 'orders:create_order' %}">Continue</a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
{% else %}
    <h2>Your shop cart is empty</h2>
{% endif %}