apps/products/urls.py
from django.urls import path
from . import views

app_name= 'products'
urlpatterns = [
    path('cheaper_product/',views.get_cheaper_product, name='cheaper_product'),
    path('newest_product/',views.get_newest_product, name='newest_product'),
    path('popular_product_groups/',views.popular_product_groups, name='popular_product_groups'),
    path('related_product/<slug:slug>/',views.get_related_product, name='related_product'),
    path('product_detail/<slug:slug>/',views.ProductDetailView.as_view(), name='product_detail'),
    path('product_groups/',views.ProductGroupsView.as_view(), name='product_groups'),
    path('product_by_groups/<slug:slug>/',views.ProductByGroup.as_view(), name='product_by_groups'),
    path('product_groups_partials/', views.get_product_groups, name='product_groups_partials'),
    
    path('compare_table/',views.compare_table, name='compare_table'),
    path('add_to_compare_list/',views.add_to_compare_list, name='add_to_compare_list'),
    path('delete_from_compare_list/',views.delete_from_compare_list, name='delete_from_compare_list'),
    path('status_of_compare_list/',views.status_of_compare_list, name='status_of_compare_list'),
]

onlineshop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('apps.main.urls',namespace='main')),
    path('accounts/',include('apps.accounts.urls',namespace='accounts')),
    path('products/',include('apps.products.urls',namespace='products')),
    path('orders/',include('apps.orders.urls',namespace='orders')),
    path('discounts/',include('apps.discounts.urls',namespace='discounts')),
    path('payments/',include('apps.payments.urls',namespace='payments')),
    path('feedback/',include('apps.feedback.urls',namespace='feedback')),
    path('search/',include('apps.search.urls',namespace='search')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

handler404 = 'apps.main.views.handler404'

templates/products_app/partials/cheaper_product.html
<div class="block block-products-carousel" data-layout="grid-5">
    <div class="container">
        {% include 'partials/products/root_group.html' with title='Cheapest products' %}

        <div class="product-flexbox" style="">
            {% for product in products %}
                {% include 'partials/products/product_box.html' with type=1 %}
            {% endfor %}
        </div>
    </div>
</div>

templates/products_app/partials/compare_table.html
{% if products %}
    <div class="container">
        <h2 style="text-align: center; color: green;">Choisen product for comparsion</h2>
        <table class="table table-bordered">
            <tr style="background: #f1f1f1; text-align: center;">
                <th>Product/Feature Product</th>
                {% for product in products %}
                    <th>
                        <i class="fa fa-times product_remove" onclick="deleteFormCompareList({{product.id}})"></i>
                        {{product.product_name}}
                    </th>
                {% endfor %}
            </tr>
            {% for feature in features %}
                <tr>
                    <td style="font-size: 1.2rem; font-weight: 900; width: 25%;">{{feature}}</td>
                    {% for product in products %}
                        <td style="text-align: center;">
                            {% for item in product.product_features.all %}
                                {% if item.feature == feature %}
                                    <span style="margin: 5px;">{{item.filter_value.value_title}}</span>
                                {% endif %}
                            {% endfor %}
                        </td>
                    {% endfor %}
                </tr>
            {% endfor %}
        </table>
    </div>
{% else %}
    <div class="container">
        <h2 style="text-align: center; color: green; padding: 100px;">No any product foor Comparsion</h2>
    </div>
{% endif %}

templates/products_app/partials/newest_product.html
<div class="block block-products-carousel" data-layout="grid-5">
    <div class="container">
        {% include 'partials/products/root_group.html' with title='Newest product' %}

        <div class="product-flexbox" style="">
            {% for product in products %}
                {% include 'partials/products/product_box.html' with type=2 %}
            {% endfor %}
        </div>
    </div>
</div>

templates/products_app/partials/popular_product_groups.html
<div class="block block--highlighted block-categories block-categories--layout--compact">
    <div class="container">
        <div class="block-header">
            <h3 class="block-header__title">Popular group products</h3>
            <div class="block-header__divider"></div>
        </div>
        <div class="block-categories__list">

            {% for group in product_group %}
            <div class="block-categories__item category-card category-card--layout--compact">
                <div class="category-card__body">
                    <div class="category-card__image">
                        <a href="{% url 'products:product_by_groups' slug=group.slug %}">
                            <img src="{{media_url}}{{group.image_name}}" alt="">
                        </a>
                    </div>
                    <div class="category-card__content">
                        <div class="category-card__name">
                            <a href="{% url 'products:product_by_groups' slug=group.slug %}">{{group.group_title}}</a>
                        </div>
                        <div class="category-card__products">product {{group.products_of_groups.all|length }}</div>
                    </div>
                </div>
            </div>
            {% endfor %}
            <a href="{% url 'products:product_groups' %}">All</a> 
        </div>
    </div>
</div>

templates/products_app/partials/product_groups.html
<ul class="filter-categories__list">
    {% for group in product_groups %}
        <li class="filter-categories__item filter-categories__item--parent">
            <a  href="{% url 'products:products_of_groups' slug=group.slug %}"></a>
            <div class="filter-categories__counter">{{group.products_of_groups.all|length}}</div>
        </li>
    
    {% endfor %}

</ul>

templates/products_app/partials/related_product.html
{% if related_product %}
    <div class="block block-products-carousel" data-layout="grid-5">
        <div class="container">
            {% include 'partials/products/root_group.html' with title='Related products' %}

            <div class="product-flexbox" style="">
                {% for product in related_product %}
                    {% include 'partials/products/product_box.html' with type=1 %}
                {% endfor %}
            </div>
        </div>
    </div>
{% endif %}