apps/accounts/urls.py
from django.urls import path
from . import views

app_name= 'accounts'
urlpatterns = [
    path('register/',views.UserRegisterView.as_view(), name='register'),
    path('verify/',views.VerifyRegisterCodeView.as_view(), name='verify'),
    path('login/',views.LoginUserView.as_view(), name='login'),
    path('logout/',views.LogoutUserView.as_view(), name='logout'),
    
    path('userpanel/',views.UserPanelView.as_view(), name='userpanel'), 
    path('show_last_orders',views.show_last_orders, name='show_last_orders'), 
    path('show_user_payments',views.show_user_payments, name='show_user_payments'), 
    path('change_password/',views.ChangePasswordView.as_view(), name='change_password'), 
    path('remember_password/',views.RememberPasswordView.as_view(), name='remember_password'), 
]

onlineshop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('apps.main.urls',namespace='main')),
    path('accounts/',include('apps.accounts.urls',namespace='accounts')),
    path('products/',include('apps.products.urls',namespace='products')),
    path('orders/',include('apps.orders.urls',namespace='orders')),
    path('discounts/',include('apps.discounts.urls',namespace='discounts')),
    path('payments/',include('apps.payments.urls',namespace='payments')),
    path('feedback/',include('apps.feedback.urls',namespace='feedback')),
    path('search/',include('apps.search.urls',namespace='search')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

handler404 = 'apps.main.views.handler404'

templates/main_template.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Online Shop - {% block title %}{% endblock title %}</title>
    <link rel="icon" type="image/png" href="images/favicon.png">
	<!-- css -->
	<link rel="stylesheet" href="{% static 'vendor/bootstrap-4.5.3/css/bootstrap.min.css' %} ">
	<link rel="stylesheet" href="{% static 'vendor/owl-carousel-2.3.4/assets/owl.carousel.min.css' %} ">
	<link rel="stylesheet" href="{% static 'css/style.css' %} ">
	<link rel="stylesheet" href="{% static 'css/custom.css' %} ">
	<!-- js -->
	<script src="{% static 'vendor/jquery-3.3.1/jquery.min.js' %} "></script>
	<script src="{% static 'vendor/bootstrap-4.5.3/js/bootstrap.bundle.min.js' %} "></script>
	<script src="{% static 'vendor/owl-carousel-2.3.4/owl.carousel.min.js' %} "></script>
	<script src="{% static 'js/main.js' %} "></script>
	<script src="{% static 'js/script.js' %} "></script>
	<!-- font - fontawesome -->
	<link rel="stylesheet" href="{% static 'vendor/fontawesome-5.6.3/css/all.min.css' %} ">
</head>
<body>
    {% include 'partials/header.html' %}

	{% include 'partials/message.html' %}

    {% block content %}
    {% endblock content %}

    {% include 'partials/footer.html' %}
</body>
</html>

templates/user_panel_template.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Online Shop - {% block title %}{% endblock title %}</title>
    <link rel="icon" type="image/png" href="images/favicon.png">
	<!-- css -->
	<link rel="stylesheet" href="{% static 'vendor/bootstrap-4.5.3/css/bootstrap.min.css' %} ">
	<link rel="stylesheet" href="{% static 'vendor/owl-carousel-2.3.4/assets/owl.carousel.min.css' %} ">
	<link rel="stylesheet" href="{% static 'css/style.css' %} ">
	<link rel="stylesheet" href="{% static 'css/custom.css' %} ">
	<!-- js -->
	<script src="{% static 'vendor/jquery-3.3.1/jquery.min.js' %} "></script>
	<script src="{% static 'vendor/bootstrap-4.5.3/js/bootstrap.bundle.min.js' %} "></script>
	<script src="{% static 'vendor/owl-carousel-2.3.4/owl.carousel.min.js' %} "></script>
	<script src="{% static 'js/main.js' %} "></script>
	<script src="{% static 'js/script.js' %} "></script>
	<!-- font - fontawesome -->
	<link rel="stylesheet" href="{% static 'vendor/fontawesome-5.6.3/css/all.min.css' %} ">
</head>

<body>
    {% include 'partials/header.html' %}
	{% include 'partials/message.html' %}

    		<!-- site__body -->
		<div class="site__body">
			<div class="page-header">
				<div class="page-header__container container">
					<div class="page-header__breadcrumb">
						<nav aria-label="breadcrumb">
							<ol class="breadcrumb">
								<li class="breadcrumb-item"><a href="user-dashboard.html">Dashboard</a>
									/
								</li>
								<li class="breadcrumb-item active" aria-current="page">Edit profile</li>
							</ol>
						</nav>
					</div>
					<div class="page-header__title">
						<h1>User Panel</h1></div>
				</div>
			</div>
			<div class="block">
				<div class="container">
					<div class="row">
						<div class="col-12 col-lg-3 d-flex">
							<div class="account-nav flex-grow-1">
								<h4 class="account-nav__title">Menu</h4>
								<ul>
									<li class="account-nav__item account-nav__item--active"><a href="{% url 'accounts:userpanel' %}">Dashboard</a></li>
									<li class="account-nav__item"><a href="{% url 'accounts:update_profile' %}">Edit Profile</a></li>
									<li class="account-nav__item"><a href="{% url 'accounts:show_user_payments' %}">Buy History</a></li>
									<li class="account-nav__item"><a href="{% url 'accounts:change_password' %}">Change Password</a></li>
									<li class="account-nav__item"><a href="{% url 'accounts:logout' %}">Logout</a></li>
								</ul>
							</div>
						</div>
						<div class="col-12 col-lg-9 mt-4 mt-lg-0">
                            {% block content %}
                            {% endblock content %}
						</div>
					</div>
				</div>
			</div>
		</div>


    {% include 'partials/footer.html' %}
</body>
</html>